language: scala
scala: 2.12.3

cache:
  directories:
  - $HOME/.sbt
  - $HOME/.m2

script:
  sbt/sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
