language: scala
scala: 2.12.3
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.sbt
  - $HOME/.m2

before_cache:
  - find $HOME/.ivy2 -name \"ivydata-*.properties\" -delete
  - find $HOME/.sbt -name \"*.lock\" -delete

before_script:
  - unset SBT_OPTS

script:
  sbt/sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
